she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # each url brings us to a specific page. this brings us to index. so when we create a url pattern, it will already start from news/ because it was defined in the main folder
    # views.IndexView = views(refers views.py and the specific class within that page)
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    # sending us to specific primary key (the page). by default, django gives a story each unique identifier
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    # path('<int:pk>', views.AuthorProfileView.as_view(), name="profileDetail")
    path('edit/<int:pk>', views.EditStoryView.as_view(), name='editStory'),
    path('delete/<int:pk>', views.deleteStoryView.as_view(), name='deleteStory'),
   ]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

# hese urls control everything inside the other urls

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, AccountPageView, EditAccountView

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(),name='createAccount'),
    path('<int:pk>/', AccountPageView.as_view(), name='accountpage'),
    path('edit-account/', EditAccountView.as_view(), name='editAccount'),
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models

class Category(models.Model):
    category_name = models.CharField(max_length=25)
    def __str__(self):
        return self.category_name

class NewsStory(models.Model):
    class Meta:
        ordering = ['-pub_date'] #added for ordering dates

    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image_url = models.URLField(blank=True,null=True)
    newsCategory = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)

she_codes_news/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    name = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank = True, null=True)
    email = models.TextField(blank = True, null=True)
    profile_picture = models.URLField(blank = True, null=True)
    linkedin = models.URLField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)
    github = models.URLField(blank=True, null=True)


    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory, Category

choices = Category.objects.all().values_list

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'newsCategory', 'content', 'image_url']
        widgets = {
            'pub_date': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date','type':'date'}),
            'newsCategory': forms.Select(attrs={'class':'form-control'})
}

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'name', 'email', 'profile_picture', 'linkedin', 'instagram', 'github']

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'name', 'email', 'profile_picture', 'linkedin', 'instagram', 'github']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory, Category
from .forms import StoryForm
from django.contrib.auth import get_user_model

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.all().order_by('-pub_date') #new addtion from orderby
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'
# the only logic applied to this within the html is just defining how the title and content has been displayed

class AuthorProfileView(generic.DetailView):
    model = get_user_model()
    template_name = 'news/profileDetail.html'
    context_object_name = 'story'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author_stories'] = NewsStory.objects.filter(author='author')
        return context

class CategoryView(generic.ListView):
        template_name = 'news/categoryView.html'
        model = NewsStory, Category

        def get_queryset(self):
            '''Return all news stories in chosen category.'''
            return NewsStory.objects.all(Category)

        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['categorised_stories'] = NewsStory.objects.all(Category).order_by('-pub_date')[:4]
            return context

class EditStoryView(generic.edit.UpdateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    model = NewsStory
    template_name = 'news/editStory.html'
    success_url = reverse_lazy('news:story')

    def get_success_url(self):
        print(self.request.user.id)
        print(type(self.get_form()))
        return reverse_lazy('users:profile', kwargs={"pk":self.request.user.id})
        
    def get_object(self):
        return self.request.user

class deleteStoryView(generic.edit.DeleteView):
    model = NewsStory
    template_name = 'news/deleteStory.html'
    success_url = reverse_lazy('news:index')

    def get_object(self):
        return self.request.user

she_codes_news/users/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm, CustomUserChangeForm

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class AccountPageView(generic.DetailView):
    model = CustomUser
    template_name = 'users/accountpage.html'
    context_object_name: 'CustomUser'

class EditAccountView(generic.UpdateView):
    form_class = CustomUserChangeForm
    model = CustomUser
    ssuccess_url = reverse_lazy('users:accountpage')
    template_name = 'users/editAccount.html'

    def get_success_url(self):
        print(self.request.user.id)
        print(type(self.get_form()))
        return reverse_lazy('users:profile', kwargs={"pk":self.request.user.id})
        
    def get_object(self):
        return self.request.user

she_codes_news/news/templates/news/categoryView.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}



<h2>{{ story.newsCategory }}</h2>
    <div>
        {% if latest_stories %}
            {% for story in latest_stories %}
            {% include "./storyCard.html" with story=story position=forloop.counter %}
                <p>{{ story.title }}</p>
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
                <p>{{ story.title }}</p>
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="submit">
</form>

{% endblock %}

she_codes_news/news/templates/news/deleteStory.html
{% extends "base.html" %}

{% block content %}
<h3> Are you sure you want to delete your post ?</h3>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <br>
    <button>Delete Post</button>
</form>
{% endblock %}

she_codes_news/news/templates/news/editStory.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button>Update</button>
</form>
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div>
{% if request.user.is_authenticated %}
<a href="{% url 'news:newStory' %}">Write New Story</a>
{% endif %}
</div>

<h2>Latest News</h2>
    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
            {% include "./storyCard.html" with story=story position=forloop.counter %}
                <p>{{ story.title }}</p>
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
                <p>{{ story.title }}</p>
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.newsCategory }}</h4>
    <a href="{% url 'users:accountpage' story.author.id %}">
        {{ story.author }}</a>
    <div id="story-content">
        {% if story.image_url %}
        <img src="{{ story.image_url }}">
        {% else %}
        <img src="https://picsum.photos/300?random={{ story.id }}">
        {% endif %}
    
        {{ story.content|linebreaks }}
    </div>
</div>

<br>
<br>
<br>
<br>

{% if request.user.is_authenticated %}
<button>
    <a href="{% url 'news:editStory' story.author.id %}">Edit Story</a>
</button>
<br>
<br>
<button>
<a href="{% url 'news:deleteStory' story.author.id %}">Delete Story</a>
</button>
{% endif %}

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        <!-- {% if position < 5 %}
            <img src="../static/news/images/placeholder-{{ position }}.jpg">
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %} -->

        {% if story.image_url %}
            <img src="{{ story.image_url }}">
        {% else %}
            <img src="https://picsum.photos/300?random={{ story.id }}">
        {% endif %}

        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Hayley van Waas">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
            {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
    {% block content %}{% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>

    {% if request.user.is_authenticated %}
    <a href="{% url 'users:accountpage' user.id %}">{{ user.username }}</a>
    <a href="{% url 'logout' %}">Logout</a>

    {% else %}
    <a href="{% url 'login' %}">Login</a>
    <a href="{% url 'users:createAccount' %}">Create Account</a>

    {% endif %}
</nav>

she_codes_news/users/templates/users/accountpage.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div>
    <h3>Profile of: {{ user.name }}</h3>
    <h4>Email: {{ user.email }}</h4>
    <img height=300px src="{{ user.profile_picture }}">
    <h4>Linkedin: {{ user.linkedin }}</h4>
</div>

<h4>Articles posted by {{ user.name }}</h4>
<ul>
{% for story in customuser.newsstory_set.all %}
    <li>{{ story.title }}</li>
{% endfor %}
</ul>

<!-- edit function -->
{% if request.user == customuser %}

<button id="edit-profile-button">
  <a href="{% url 'users:editAccount' %}">Edit Profile</a></button>

<div class="user-add-story">
  </br>
  <button id="new-story-button">
    <a href="{% url 'news:newStory' %}">Write New Story</a></button>
</div>

{% endif %}

{% endblock %}

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
<h2>Create Account</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Account</button>
</form>
{% endblock %}

she_codes_news/users/templates/users/editAccount.html
{% extends 'base.html' %}
{% block content %}
<h3 id="welcome-user">Welcome {{ user.name }}</h3>
<p id="edit-page-txt">Edit your profile here!</p>
<div>
  <h2 id="edit-account-title">Edit Your Profile</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button id="confirm-edit-profile-btn" type="submit" name="confirm">Confirm Profile Info</button>
    </br>
  </br>
  <button id="skip-edit-btn" type="submit" name="skip">Skip</button>
  </form>
</div>
{% endblock %}